=== LaBrush/SIRescue/resources/config/game.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="game">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="armes">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="arme" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
									<xs:attribute name="tir" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="Resistance" />
												<xs:enumeration value="Transistor" />
												<xs:enumeration value="Echarpe" />
												<xs:enumeration value="Bouclier" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="damage" type="xs:integer" use="required"></xs:attribute>
									<xs:attribute name="recul" type="xs:integer" use="required"></xs:attribute>
									<xs:attribute name="reload" type="xs:integer" use="required"></xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="botTypes">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="botType" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
									<xs:attribute name="arme" type="xs:string" use="required"></xs:attribute>
									<xs:attribute name="life" type="xs:integer" use="required"></xs:attribute>
									<xs:attribute name="comportement">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="FlyBotBehaviour" />
												<xs:enumeration value="ToucherBotBehaviour" />
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="levels">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="level" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="src" type="xs:string" use="required"></xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== LaBrush/SIRescue/resources/config/game.xml
<?xml version="1.0" encoding="UTF-8" ?>
<game xs:noNamespaceSchemaLocation="game.xsd"
	xmlns:xs="http://www.w3.org/2001/XMLSchema-instance">

	<armes>
		<arme name="Bouclier" tir="Bouclier" damage="20" recul="300"
			reload="3" />
		<arme name="Resistance" tir="Resistance" damage="20" recul="0"
			reload="300" />
		<arme name="Transistor" tir="Transistor" damage="40" recul="400"
			reload="50" />
	</armes>

	<botTypes>
		<botType name="bino" arme="Bouclier" comportement="ToucherBotBehaviour"
			life="1000" />
		<botType name="soso" arme="Resistance" comportement="FlyBotBehaviour"
			life="50" />
	</botTypes>

	<levels>
		<level src="level1.xml" />
		<level src="level2.xml" />
		<level src="level3.xml" />
	</levels>

</game>
