=== LaBrush/SIRescue/resources/config/level.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">

	<xs:element name="level">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="hero">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="life" type="xs:string"></xs:element>
							<xs:element name="position" type="position"></xs:element>
							<xs:element name="arme" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="cartouches" type="xs:integer"></xs:attribute>
									<xs:attribute name="type" type="xs:string" use="required"></xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="blocs">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="bloc" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="position" type="position"></xs:element>
										<xs:element name="dimensions" type="dimensions">
										</xs:element>
									</xs:sequence>
									<xs:attribute name="id" type="xs:integer"></xs:attribute>
									<xs:attribute name="hurting" type="xs:boolean"></xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="items">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="item" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="position" type="position"></xs:element>
										<xs:element name="dimensions" type="dimensions"></xs:element>
									</xs:sequence>
									<xs:attribute name="content" type="xs:string"></xs:attribute>
									<xs:attribute name="type" type="xs:string"></xs:attribute>
									<xs:attribute name="cartouches" type="xs:integer"></xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>

				<xs:element name="bots">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="bot" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="type" type="xs:string"></xs:element>
										<xs:element name="position" type="position"></xs:element>
										<xs:element name="bloc_id" type="xs:integer"
											minOccurs="0"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="position">
		<xs:attribute name="x" type="xs:int" use="required"></xs:attribute>
		<xs:attribute name="y" type="xs:int" use="required"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="dimensions">
		<xs:attribute name="width" type="xs:int" use="required"></xs:attribute>
		<xs:attribute name="height" type="xs:int" use="required"></xs:attribute>
	</xs:complexType>

</xs:schema>

=== LaBrush/SIRescue/resources/config/level3.xml
<?xml version="1.0" encoding="UTF-8"?>
<level xs:noNamespaceSchemaLocation="level.xsd"
	xmlns:xs="http://www.w3.org/2001/XMLSchema-instance">

	<hero>
		<life>200</life>
		<position x="150" y="20" />
		<arme cartouches="-1" type="Echarpe" />
	</hero>

	<blocs>
		<!--contours -->
		<bloc>
			<position x="0" y="720" />
			<dimensions width="1080" height="10" />
		</bloc>
		<bloc>
			<position x="1080" y="0" />
			<dimensions width="10" height="720" />
		</bloc>
		<bloc>
			<position x="-11" y="0" />
			<dimensions width="10" height="720" />
		</bloc>
		<!--sol -->
		<bloc id="2">
			<position x="0" y="0" />
			<dimensions width="1080" height="10" />
		</bloc>

		<!--plafond -->
		<bloc>
			<position x="0" y="660" />
			<dimensions width="1080" height="30" />
		</bloc>
		<bloc hurting="true">
			<position x="0" y="610" />
			<dimensions width="1080" height="49" />
		</bloc>

		<!-- plateforme F -->
		<bloc>
			<position x="0" y="10" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="0" y="40" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="0" y="70" />
			<dimensions width="75" height="20" />
		</bloc>
		<bloc>
			<position x="0" y="100" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="0" y="130" />
			<dimensions width="115" height="20" />
		</bloc>
		<!-- plateforme E -->
		<bloc>
			<position x="241" y="130" />
			<dimensions width="115" height="20" />
		</bloc>
		<bloc>
			<position x="241" y="160" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="241" y="190" />
			<dimensions width="75" height="20" />
		</bloc>
		<bloc>
			<position x="241" y="220" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc id="3">
			<position x="241" y="250" />
			<dimensions width="115" height="20" />
		</bloc>
		<!-- plateforme L -->
		<bloc>
			<position x="482" y="130" />
			<dimensions width="115" height="20" />
		</bloc>
		<bloc>
			<position x="482" y="160" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="482" y="190" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="482" y="220" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="482" y="250" />
			<dimensions width="35" height="20" />
		</bloc>
		<!-- plateforme C -->
			<bloc>
			<position x="723" y="130" />
			<dimensions width="115" height="20" />
		</bloc>
		<bloc>
			<position x="723" y="160" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="723" y="190" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="723" y="220" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="723" y="250" />
			<dimensions width="115" height="20" />
		</bloc>
		<!-- plateforme O -->
		<bloc>
			<position x="960" y="130" />
			<dimensions width="115" height="20" />
		</bloc>
		<bloc>
			<position x="960" y="100" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="1040" y="100" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="960" y="70" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="1040" y="70" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="960" y="40" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="1040" y="40" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="960" y="10" />
			<dimensions width="115" height="20" />
		</bloc>
		
		

		<bloc id="1">
			<position x="0" y="130" />
			<dimensions width="115" height="20" />
		</bloc>
		<bloc>
			<position x="0" y="130" />
			<dimensions width="115" height="20" />
		</bloc>
	</blocs>

	<items>
		<item content="arme" type="Transistor" cartouches="20">
			<position x="540" y="360" />
			<dimensions width="20" height="20" />
		</item>
	</items>

	<bots>

		<bot>
			<type>bino</type>
			<position x="250" y="220" />
			<bloc_id>1</bloc_id>
		</bot>
		
		<bot>
			<type>bino</type>
			<position x="250" y="220" />
			<bloc_id>2</bloc_id>
		</bot>
		
		<bot>
			<type>bino</type>
			<position x="250" y="220" />
			<bloc_id>3</bloc_id>
		</bot>
		
		<bot>
			<type>soso</type>
			<position x="200" y="50" />
		</bot>
		<bot>
			<type>dudu</type>
			<position x="960" y="250" />
		</bot>
	</bots>
</level>

=== LaBrush/SIRescue/resources/config/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<level xs:noNamespaceSchemaLocation="level.xsd"
	xmlns:xs="http://www.w3.org/2001/XMLSchema-instance">
	
	<hero>
		<life>100</life>
		<position x="15" y="20" />
		<arme cartouches="300" type="Resistance" />
		<arme cartouches="300" type="Echarpe" />
	</hero>
	<blocs>
		<!--contours -->
		<bloc>
			<position x="0" y="720" />
			<dimensions width="1080" height="10" />
		</bloc>
		<bloc>
			<position x="1080" y="0" />
			<dimensions width="10" height="720" />
		</bloc>
		<bloc>
			<position x="-11" y="0" />
			<dimensions width="10" height="720" />
		</bloc>
		<!--sol -->
		<bloc>
			<position x="0" y="0" />
			<dimensions width="80" height="10" />
		</bloc>
	</blocs>

	<items>
		<item content="arme" type="Transistor" cartouches="20">
			<position x="530" y="410" />
			<dimensions width="20" height="20" />
		</item>

		<item>
			<position x="1030" y="10" />
			<dimensions width="15" height="60" />
		</item>
	</items>

	<bots>
		<bot>
			<type>soso</type>
			<position x="350" y="520" />
		</bot>
	</bots>
</level>

=== LaBrush/SIRescue/resources/config/level2.xml
<?xml version="1.0" encoding="UTF-8"?>
<level xs:noNamespaceSchemaLocation="level.xsd"
	xmlns:xs="http://www.w3.org/2001/XMLSchema-instance">
	
	<music src="resources/audio/musique_lvl2.wav"/>
	
	<hero>
		<life>1000</life>
		<position x="15" y="20" />
		<arme cartouches="300" type="Resistance" />
	</hero>

	<blocs>
		<!--contours -->
		<bloc>
			<position x="0" y="720" />
			<dimensions width="1080" height="10" />
		</bloc>
		<bloc>
			<position x="1080" y="0" />
			<dimensions width="10" height="720" />
		</bloc>
		<bloc>
			<position x="-11" y="0" />
			<dimensions width="10" height="720" />
		</bloc>
		<!--sol -->
		<bloc>
			<position x="0" y="0" />
			<dimensions width="80" height="10" />
		</bloc>
		<bloc hurting="true">
			<position x="80" y="0" />
			<dimensions width="900" height="10" />
		</bloc>
		<bloc>
			<position x="980" y="0" />
			<dimensions width="100" height="10" />
		</bloc>
		<!--plafond -->
		<bloc>
			<position x="0" y="660" />
			<dimensions width="1080" height="30" />
		</bloc>
		<bloc hurting="true">
			<position x="0" y="610" />
			<dimensions width="670" height="49" />
		</bloc>
		<bloc hurting="true">
			<position x="730" y="610" />
			<dimensions width="350" height="49" />
		</bloc>
		<!-- plateforme:A -->
		<bloc>
			<position x="100" y="42" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="148" y="42" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="100" y="64" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="148" y="64" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="100" y="86" />
			<dimensions width="72" height="14" />
		</bloc>
		<bloc>
			<position x="100" y="108" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="148" y="108" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="100" y="130" />
			<dimensions width="72" height="14" />
		</bloc>
		<!-- plateforme:D -->
		<bloc>
			<position x="222" y="130" />
			<dimensions width="48" height="14" />
		</bloc>
		<bloc>
			<position x="222" y="152" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="270" y="152" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="222" y="174" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="270" y="174" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="222" y="196" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="270" y="196" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="222" y="218" />
			<dimensions width="48" height="14" />
		</bloc>
		<!-- plateforme:V -->
		<bloc>
			<position x="368" y="218" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="351" y="240" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="385" y="240" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="344" y="262" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="392" y="262" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="344" y="284" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="392" y="284" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="344" y="306" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="392" y="306" />
			<dimensions width="24" height="14" />
		</bloc>
		<!-- plateforme:I -->
		<bloc>
			<position x="466" y="306" />
			<dimensions width="72" height="14" />
		</bloc>
		<bloc>
			<position x="490" y="328" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="490" y="350" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="490" y="372" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="466" y="394" />
			<dimensions width="72" height="14" />
		</bloc>
		<!-- plateforme:S -->
		<bloc>
			<position x="588" y="306" />
			<dimensions width="72" height="14" />
		</bloc>
		<bloc>
			<position x="588" y="284" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="588" y="262" />
			<dimensions width="72" height="14" />
		</bloc>
		<bloc>
			<position x="636" y="240" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="588" y="218" />
			<dimensions width="72" height="14" />
		</bloc>
		<!-- plateforme:E -->
		<bloc>
			<position x="710" y="218" />
			<dimensions width="72" height="14" />
		</bloc>
		<bloc>
			<position x="710" y="196" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="710" y="174" />
			<dimensions width="48" height="14" />
		</bloc>
		<bloc>
			<position x="710" y="152" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="710" y="130" />
			<dimensions width="72" height="14" />
		</bloc>
		<!-- plateforme:N -->
		<bloc>
			<position x="832" y="130" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="904" y="130" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="832" y="108" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="904" y="108" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="832" y="86" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="904" y="86" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="832" y="64" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="904" y="64" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="832" y="42" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="904" y="42" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="861" y="98" />
			<dimensions width="24" height="14" />
		</bloc>
		<bloc>
			<position x="875" y="74" />
			<dimensions width="24" height="14" />
		</bloc>


		<bloc id="1">
			<position x="466" y="394" />
			<dimensions width="72" height="14" />
		</bloc>

		<bloc hurting="true">
			<position x="300" y="100" />
			<dimensions width="40" height="30" />
		</bloc>
	</blocs>

	<items>
		<item>
			<position x="1060" y="11" />
			<dimensions width="20" height="60" />
		</item>
	</items>

	<bots>
		<bot>
			<type>bino</type>
			<position x="170" y="125" />
			<bloc_id>1</bloc_id>
		</bot>

		<bot>
			<type>soso</type>
			<position x="150" y="220" />
		</bot>

	</bots>
</level>

=== LaBrush/SIRescue/resources/config/level1.xml
<?xml version="1.0" encoding="UTF-8"?>
<level xs:noNamespaceSchemaLocation="level.xsd"
	xmlns:xs="http://www.w3.org/2001/XMLSchema-instance">
	<hero>
		<life>100</life>
		<position x="15" y="20" />
		<arme cartouches="300" type="Resistance" />
	</hero>
	<blocs>
		<!--contours -->
		<bloc>
			<position x="0" y="720" />
			<dimensions width="1080" height="10" />
		</bloc>
		<bloc>
			<position x="1080" y="0" />
			<dimensions width="10" height="720" />
		</bloc>
		<bloc>
			<position x="-11" y="0" />
			<dimensions width="10" height="720" />
		</bloc>
		<!--sol -->
		<bloc>
			<position x="0" y="0" />
			<dimensions width="80" height="10" />
		</bloc>
		<bloc hurting="true">
			<position x="79" y="0" />
			<dimensions width="20" height="10" />
		</bloc>
		<bloc hurting="true">
			<position x="136" y="0" />
			<dimensions width="845" height="10" />
		</bloc>
		<bloc>
			<position x="980" y="0" />
			<dimensions width="100" height="10" />
		</bloc>
		<!--plafond -->
		<bloc>
			<position x="0" y="660" />
			<dimensions width="1080" height="30" />
		</bloc>
		<bloc hurting="true">
			<position x="0" y="610" />
			<dimensions width="710" height="49" />
		</bloc>
		<bloc hurting="true">
			<position x="770" y="610" />
			<dimensions width="350" height="49" />
		</bloc>
		<!--plateformes:F -->
		<bloc>
			<position x="100" y="1" />
			<dimensions width="35" height="10" />
		</bloc>
		<bloc>
			<position x="100" y="20" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="100" y="55" />
			<dimensions width="75" height="20" />
		</bloc>
		<bloc>
			<position x="100" y="90" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="100" y="125" />
			<dimensions width="115" height="20" />
		</bloc>
		<!--plateformes:E -->
		<bloc>
			<position x="315" y="120" />
			<dimensions width="115" height="20" />
		</bloc>
		<bloc>
			<position x="315" y="155" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="315" y="190" />
			<dimensions width="75" height="20" />
		</bloc>
		<bloc>
			<position x="315" y="225" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="315" y="260" />
			<dimensions width="115" height="20" />
		</bloc>
		<bloc hurting="true">
			<position x="275" y="225" />
			<dimensions width="39" height="20" />
		</bloc>
		<bloc hurting="true">
			<position x="275" y="190" />
			<dimensions width="39" height="20" />
		</bloc>
		<!--plateformes:S -->
		<bloc>
			<position x="530" y="225" />
			<dimensions width="115" height="20" />
		</bloc>
		<bloc>
			<position x="610" y="260" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="530" y="295" />
			<dimensions width="115" height="20" />
		</bloc>
		<bloc>
			<position x="530" y="330" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="530" y="365" />
			<dimensions width="115" height="20" />
		</bloc>
		<!--plateformes:T -->
		<bloc>
			<position x="785" y="330" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="785" y="365" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="785" y="400" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="785" y="435" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="745" y="470" />
			<dimensions width="115" height="20" />
		</bloc>
		<!--plateformes:O -->
		<bloc>
			<position x="960" y="400" />
			<dimensions width="115" height="20" />
		</bloc>
		<bloc>
			<position x="960" y="365" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="1040" y="365" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="960" y="330" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="1040" y="330" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="960" y="295" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="1040" y="295" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="960" y="260" />
			<dimensions width="115" height="20" />
		</bloc>
		<bloc hurting="true">
			<position x="960" y="210" />
			<dimensions width="115" height="49" />
		</bloc>



		<bloc>
			<position x="770" y="130" />
			<dimensions width="115" height="20" />
		</bloc>
		<bloc hurting="true">
			<position x="100" y="280" />
			<dimensions width="115" height="49" />
		</bloc>
		<bloc id="1">
			<position x="100" y="330" />
			<dimensions width="115" height="30" />
		</bloc>
	</blocs>

	<items>
		<item content="arme" type="Transistor" cartouches="20">
			<position x="730" y="610" />
			<dimensions width="20" height="20" />
		</item>

		<item>
			<position x="1030" y="10" />
			<dimensions width="15" height="60" />
		</item>
	</items>

	<bots>
		<bot>
			<position x="170" y="125" />
			<type>bino</type>
			<bloc_id>1</bloc_id>
		</bot>
		<bot>
			<position x="150" y="220" />
			<type>soso</type>
		</bot>
	</bots>
</level>
