=== LaBrush/SIRescue/resources/Level.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="level">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="hero">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="position" type="position"></xs:element>
							<xs:element name="arme">
								<xs:complexType>
									<xs:attribute name="type" type="xs:string" use="required"></xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="bots">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="bot">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="position" type="position"></xs:element>
										<xs:element name="arme">
											<xs:complexType>
												<xs:attribute name="type" type="xs:string" use="required"></xs:attribute>
											</xs:complexType>
										</xs:element>
										<xs:element name="comportement" type="xs:string"></xs:element>
										<xs:element name="type" type="xs:string"></xs:element>
										<xs:element name="bloc_id" type="xs:integer"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="blocs">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="bloc" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="id" type="xs:integer" minOccurs="0"
											maxOccurs="1"></xs:element>
										<xs:element name="position" type="position"></xs:element>
										<xs:element name="dimensions">
											<xs:complexType>
												<xs:attribute name="width" type="xs:int" use="required"></xs:attribute>
												<xs:attribute name="height" type="xs:int" use="required"></xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="armes">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="arme">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="position" type="position"></xs:element>
										<xs:element name="type" type="xs:string"></xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="position">
		<xs:attribute name="x" type="xs:int" use="required"></xs:attribute>
		<xs:attribute name="y" type="xs:int" use="required"></xs:attribute>
	</xs:complexType>
</xs:schema>

=== LaBrush/SIRescue/resources/level1.xml
<?xml version="1.0" encoding="UTF-8"?>
<level xs:noNamespaceSchemaLocation="level.xsd"
	xmlns:xs="http://www.w3.org/2001/XMLSchema-instance">
	<hero>
		<life>1000</life>
		<position x="15" y="20" />
		<arme cartouches="300" type="Resistance" />
	</hero>
	<!--contours -->
	<blocs>
		<bloc>
			<position x="0" y="720" />
			<dimensions width="1080" height="10" />
		</bloc>
		<bloc>
			<position x="1080" y="0" />
			<dimensions width="10" height="720" />
		</bloc>
		<bloc>
			<position x="-11" y="0" />
			<dimensions width="10" height="720" />
		</bloc>
		<!--sol -->
		<bloc>
			<position x="0" y="0" />
			<dimensions width="80" height="10" />
		</bloc>
		<bloc hurting="true">
			<position x="80" y="0" />
			<dimensions width="900" height="10" />
		</bloc>
		<bloc>
			<position x="980" y="0" />
			<dimensions width="100" height="10" />
		</bloc>
		<!--plateformes:F -->
		<bloc>
			<position x="100" y="12" />
			<dimensions width="35" height="18" />
		</bloc>
		<bloc>
			<position x="100" y="35" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="100" y="60" />
			<dimensions width="75" height="20" />
		</bloc>
		<bloc>
			<position x="100" y="85" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="100" y="110" />
			<dimensions width="115" height="20" />
		</bloc>
		<!--plateformes:E -->
		<bloc>
			<position x="250" y="85" />
			<dimensions width="115" height="20" />
		</bloc>
		<bloc>
			<position x="250" y="120" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="250" y="155" />
			<dimensions width="75" height="20" />
		</bloc>
		<bloc>
			<position x="250" y="190" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="250" y="225" />
			<dimensions width="115" height="20" />
		</bloc>
		<!--plateformes:S -->
		<bloc>
			<position x="400" y="190" />
			<dimensions width="115" height="20" />
		</bloc>
		<bloc>
			<position x="480" y="225" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="400" y="260" />
			<dimensions width="115" height="20" />
		</bloc>
		<bloc>
			<position x="400" y="295" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="400" y="330" />
			<dimensions width="115" height="20" />
		</bloc>
		<!--plateformes:T -->
		<bloc>
			<position x="590" y="295" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="590" y="330" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="590" y="365" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="590" y="400" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="550" y="435" />
			<dimensions width="115" height="20" />
		</bloc>
		<!--plateformes:O -->
		<bloc>
			<position x="700" y="400" />
			<dimensions width="115" height="20" />
		</bloc>
		<bloc>
			<position x="700" y="365" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="780" y="365" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="700" y="330" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="780" y="330" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="700" y="295" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="780" y="295" />
			<dimensions width="35" height="20" />
		</bloc>
		<bloc>
			<position x="700" y="260" />
			<dimensions width="115" height="20" />
		</bloc>


		<bloc id="1">
			<position x="1000" y="650" />
			<dimensions width="30" height="30" />
		</bloc>
		<bloc ender="true">
			<position x="500" y="0" />
			<dimensions width="40" height="10" />
		</bloc>
	</blocs>

	<items>
		<item content="arme" type="Transistor" cartouches="20">
			<position x="50" y="12" />
			<dimensions width="20" height="20" />
		</item>
	</items>

	<bots>
		<bot>
			<position x="170" y="125" />
			<type>bino</type>
			<bloc_id>1</bloc_id>
		</bot>
		<bot>
			<position x="150" y="220" />
			<type>soso</type>
		</bot>
	</bots>
</level>

=== LaBrush/SIRescue/resources/Level.xml
<?xml version="1.0" encoding="UTF-8"?>
<level xs:noNamespaceSchemaLocation="Level.xsd"
	xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" >
	<hero>
		<position x="15" y="20" />
		<arme type="resistance" />
	</hero>

	<bots>
		<bot>
			<position x="150" y="20" />
			<arme type="resistance" />
			<comportement>abstractbehaviour</comportement>
			<type>Soso</type>
			<bloc_id>1</bloc_id>
		</bot>
	</bots>

	<blocs>
		<bloc>
			<position x="0" y="370" />
			<dimensions width="600" height="10" />
		</bloc>
		<bloc>
			<position x="590" y="0" />
			<dimensions width="10" height="400" />
		</bloc>
		<bloc>
			<position x="0" y="0" />
			<dimensions width="600" height="10" />
		</bloc>
		<bloc>
			<position x="0" y="0" />
			<dimensions width="10" height="400" />
		</bloc>
		<bloc>
			<id>1</id>
			<position x="50" y="100" />
			<dimensions width="50" height="100" />
		</bloc>
	</blocs>

	<!-- <armes>
		<arme>
			<position x="200" y="300" />
			<type>resistance</type>
		</arme>
	</armes>
	-->
</level>
